[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.primary]
background = "#282A2E"
bright_foreground = "0xe6efff"
foreground = "0xabb2bf"

[font]
size = 14

[font.normal]
family = "Monocraft"
style = "Regular"

[window.padding]
x = 20
y = 20
